### PR TITLE
improve the core example snippet

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Review by tsikerdekis — APPROVED** [review]
Excellent, thank you for the updated example code.

**Comment by monperrus** [comment]
Super.

Is there any code to generate nice graphics from the tsv files?

**Comment by tsikerdekis** [comment]
I have messy R files that I used for the tests in the paper and for the graphics (polar coordinate graphs for the top 15 users). Easiest way would be to just load the tsv in libreoffice or something and use the graphics there after applying an aggregate function per username. In order to produce polar coordinates I used this code (it needs to be adapted depending on your table):
```
megadf <- megadf[order(-megadf$persistence_ownership_percent),] 
commits_c15 <- megadf[1:15,]
ec <- data.frame(name = rep(commits_c15$fakename, commits_c15$persistence_ownership_percent*1000))
cxc <- ggplot(ec, aes(x = factor(name))) +
  geom_bar(width = 1, colour = "black")
p4 <- cxc + coord_polar()+ theme_minimal()+ xlab("Persistent Authorship") + ylab("Standardized Values")
```

As we are translating the code to C (hopefully increase performance by eliminating bounds check), we will also make it so that the example scripts won't be necessary. The final outcome will be similar to running git-fame on a repo and getting back the table (or tsv). We can then also incorporate some function that can produce graphs.

If you happen to develop a script for the python example code, I would be happy to include it in the repo.

**Comment by monperrus** [comment]
I have the feeling that the numbers you compute are able to support really nice visualizations, in
the spirit of https://github.com/erikbern/git-of-theseus

Unfortunately, I cannot contribute to this but would love to try and alpha-test!

**Comment by tsikerdekis** [comment]
Thank you Martin! We can always use more feedback on testing. I agree, it looks like that with a few modifications we can produce how historically code changes. Actually, internally we can tell which character came from which revision. Ideally one can then test the possible applications like the git-of-theseus.

**Pull request merged**
